// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS7Rg-lXm46GYhzMvWeV2Vuz8LlG34tT0',
    appId: '1:422326396022:web:2730d2abbaa99fe8adeb57',
    messagingSenderId: '422326396022',
    projectId: 'complex-figure-test',
    authDomain: 'complex-figure-test.firebaseapp.com',
    storageBucket: 'complex-figure-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbftkHNMlEj3-MNC3yovjTOL3y3t01F4',
    appId: '1:422326396022:android:1089226f3da6e55fadeb57',
    messagingSenderId: '422326396022',
    projectId: 'complex-figure-test',
    storageBucket: 'complex-figure-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMJTbMrSUOUIBqgb-r6tMMAaMmESq8iDI',
    appId: '1:422326396022:ios:e1368ad2230ee3e4adeb57',
    messagingSenderId: '422326396022',
    projectId: 'complex-figure-test',
    storageBucket: 'complex-figure-test.appspot.com',
    iosClientId: '422326396022-4tvuo91v52nqrfi6j52d0ggntdeiqkrh.apps.googleusercontent.com',
    iosBundleId: 'dk.michaelguldborg.cft',
  );
}
